server:
  port: 8080

spring:
  application:
    name: admin-boot

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
  instance:
    hostname: localhost
